### ISSUE TITLE
 Excuse me, have you ever run a specific dataset? Why do I use decision tree to run and find that tradaboost is invalid? 

### ISSUE THREAD

**Issue by anyifei7752** [GianlucaPoliTo/TrAdaBoostMulticlass#1]
Excuse me, have you ever run a specific dataset? Why do I use decision tree to run and find that tradaboost is invalid?

**Comment by gianlucaperna** [comment]
Hi @anyifei7752, thanks for your feedback.
Can you share with me the error that you obtain?

**Comment by anyifei7752** [comment]
@GianlucaPoliTo  

Do you mean error rate or something else? I use the decision tree as a classifier, and the accuracy is almost the same in the two cases of adding tradaboost weight and not adding weight, and sometimes the accuracy decreases with the weight added.

**Comment by anyifei7752** [comment]
@GianlucaPoliTo  Can you send me your test program and data set?

**Comment by gianlucaperna** [comment]
Sorry @anyifei7752 actually my test program is employee in research, so I can't share the dataset until the publication of the paper. 
Do you have set a little max_depth in the decision tree classifier? 
What do you mean when you say   "not adding weight"? Have you removed the sample_weight=wt parameter?

**Comment by anyifei7752** [comment]
@GianlucaPoliTo  I set max_ Depth, without increasing the weight, the sample is removed_ weight。 Another problem is that the beta in the program is missing a log

**Comment by anyifei7752** [comment]
@GianlucaPoliTo  This program is effective in your test, isn't it?

**Comment by gianlucaperna** [comment]
Actually, I have only prepared the code, but, I'm using other transfer learning techniques.
Let's me check this code, could be an error inside.

**Comment by anyifei7752** [comment]
@GianlucaPoliTo  OK, please let me know if there is any problem. Thank you!

**Comment by gianlucaperna** [comment]
@anyifei7752 sorry for the delay, I checked the code and I corrected some errors. Let me know if now it works!

**Comment by anyifei7752** [comment]
OK. I'll try tomorrow and contact you tomorrow. Good night On 03/16/2021 01:37, Gianluca Perna wrote: 
@anyifei7752 sorry for the delay, I checked the code and I corrected some errors. Let me know if now it works!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/GianlucaPoliTo/TrAdaBoostMulticlass/issues/1#issuecomment-799611355",
"url": "https://github.com/GianlucaPoliTo/TrAdaBoostMulticlass/issues/1#issuecomment-799611355",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by anyifei7752** [comment]
Do you have WeChat? We can add a friend to communicate with each other




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gianluca ***@***.***&gt;; 
发送时间: 2021年3月16日(星期二) 凌晨1:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GianlucaPoliTo/TrAdaBoostMulticlass]  Excuse me, have you ever run a specific dataset? Why do I use decision tree to run and find that tradaboost is invalid?  (#1)





 
@anyifei7752 sorry for the delay, I checked the code and I corrected some errors. Let me know if now it works!

**Comment by gianlucaperna** [comment]
I'm sorry but I don't use WeChat. If you need details information about the code you can write here or send me an e-mail. 
If you haven't other errors I think that I can close this thread
